### ISSUE TITLE
Missing tyde definitions

### ISSUE THREAD

**Issue by teddybee** [janoist1/saga-toolkit#2]
Good afternoon,

I would like to use this lib in my typescript project, but I haven't found the types package. Could you help me where can I found or how can I use this without it in a ts file?
If mostly similar, could I use the redux toolkit`s typedef package?

**Comment by janoist1** [comment]
hey,

thanks for the interest in this package, I hope you'll find it as useful as my team does. :)

since this package is written in JS there's no TS definitions at the moment but I'm happy to add it.
if this is an urgency you can write it yourself and open a PR for this
we'll need ambient declarations (more here: https://basarat.gitbook.io/typescript/type-system/intro)
as a step 1, a very basic defs with `any`s would do it, just to suppress compile errors - to be improved later
let me know if there are any questions

**Comment by teddybee** [comment]
Thank you for the quick response, I will try it next week.
UI: Te magyar vagy.

**Comment by janoist1** [comment]
Ok, cool - thanks for the contribution.
UI Igen, magyar vagyok. :)

**Comment by teddybee** [comment]
Could we discuss it on skype some time? I have tons of questions about your code. Probably my lack of knowledge, but there are some very strange expressions for me(and the typescript compiler beeping as well).
I had made a simple type definition file for the lib, but the "any" solution is not working.
Please contact me, if you have 20-30 minutes spare time on an afternoon.

**Comment by janoist1** [comment]
Email sent.

**Comment by paveltretyakovru** [comment]
Hey, Guys! 
And what is it results of the issue? :-D Ahaha, I'm need types of the library too )))

**Comment by janoist1** [comment]
hey @paveltretyakovru ! I've had lots of work recently and we did not managed to make progress on this. will try to keep this on the radar, and keep you posted 👍
ps an help is welcome :)

**Comment by Panz99** [comment]
Any news about this issue? Maybe someone has started defining types?

**Comment by janoist1** [comment]
Me and one of my colleagues have prioritised this, and will start making
progress this week.

**Comment by janoist1** [comment]
@paveltretyakovru @teddybee @Panz99 
Can you review this PR please? https://github.com/janoist1/saga-toolkit/pull/5 It is about adding types to the package.

**Comment by paveltretyakovru** [comment]
> @paveltretyakovru @teddybee @Panz99 Can you review this PR please? #5 It is about adding types to the package.

Wow! Fantastic!
I have never works with library type difinision, but I will review the MR necessarily!
Thanks, @janoist1 for your the spended time for the work!

**Comment by janoist1** [comment]
closing this, as type defs have been added
