### ISSUE TITLE
Unable to dispatch action with saga-toolkit package

### ISSUE THREAD

**Issue by trickjsprogram** [janoist1/saga-toolkit#3]
Hi, I have tried to use ur npm-package saga-toolkit but facing some challenging to use with React & Redux-Toolkit. Already I have opened query on stackover flow if you could please look into this that will good. I am feeling something going wrong but unable to figure out

https://stackoverflow.com/questions/71545338/unable-to-dispatch-action-by-using-saga-toolkit-and-redux-toolkit-together

**Comment by janoist1** [comment]
hi,
I've added an example https://github.com/janoist1/saga-toolkit/tree/master/example
let me know is that helps

**Comment by trickjsprogram** [comment]
Thanks for the solution, I really appreciate your dedication. While running your app , I was getting below error
Module not found: Can't resolve 'history' in 'D:\saga-toolkit\saga-toolkit-master\example\src'. I think it's happen with due to createBrowserHistory .

It will be really helpful if you able to do in this repo [https://github.com/trickjsprogram/saga-redux-toolkit](url). Actually i created this project in which redux-saga is working fine with redux-toolkit without using saga-toolkit package, i mean traditional using traditional redux-saga approach . However, I tried to use your package but it was not working for me. May be if possible, you can try to use saga-tool kit [https://github.com/trickjsprogram/saga-redux-toolkit](url) in this repo. I will keep trying from my end.

**Comment by janoist1** [comment]
I'm not sure what could be the problem at your side but it runs without an error here. I've just removed `node_modules` and run `npm i`, then `npm start`.

To fix the issue with `history` you can either remove the history / connected router logic or `npm install history` (I'm not sure why it's missing though)

In your repo, once you've got a running redux project with sagas, you should be able to use the toolkit too. There are 2 point where it is imported in the example:
- in `slice.js`
- in `sagas.js`

hope this helps !

**Comment by trickjsprogram** [comment]
Thanks for your support. I will try to fix this problem. Closing this issue.
